CREATE DATABASE MASDEXO1;

USE MASDEXO1;
--EXERCICE

CREATE TABLE PERSONNE (
ID_PERS INT PRIMARY KEY IDENTITY,
PRENOM VARCHAR(50),
NOM VARCHAR(50),
NAISSANCE DATE,
PAYS VARCHAR(50)
);

INSERT INTO PERSONNE ( PRENOM, NOM, NAISSANCE, PAYS)
VALUES
('RACHID', 'ELHADRA', '1990-05-15', 'RABAT'),
('YOUNES', 'MOUSSA', '1985-08-20', 'FES'),
('ABDELLAH', 'NADIR', '1992-03-10', 'OUAZZANE'),
('HAMZA', 'KAMAL', '1999-02-15', 'TETOUAN'),
('SAID', 'AMALI', '1989-08-20', 'CHEFCHAOUEN'),
('MOHAMED', 'BOUCHTA', '1992-03-10', 'TANGER')

CREATE TABLE AGGLOMERATION (
CODE VARCHAR(5) NOT NULL,
NOM VARCHAR(255) NOT NULL,
NB_HABITANT INT NOT NULL,
PAYS VARCHAR(2) NOT NULL,
PRIMARY KEY (CODE)
);

INSERT INTO AGGLOMERATION (CODE, NOM, NB_HABITANT, PAYS) VALUES
('MA01', 'MARRAKECH', 1263442, 'MA'),
('MA02', 'CASABLANCA', 4332332, 'MA'),
('MA03', 'FES', 1220514, 'MA'),
('MA04', 'TANGER', 1065631, 'MA'),
('MA05', 'RABAT', 585255, 'MA');


-- CREATION TABLE HABITE
CREATE TABLE HABITE (
IDHABITE INT NOT NULL PRIMARY KEY IDENTITY,
ID_PERS INT NOT NULL,
CODE_AGGLO VARCHAR(5) NOT NULL,
DEBUT DATE NOT NULL,
FIN DATE,
FOREIGN KEY (ID_PERS) REFERENCES PERSONNE (ID_PERS),
FOREIGN KEY (CODE_AGGLO) REFERENCES AGGLOMERATION (CODE)
);

-- INSETION TABLE HABITE
INSERT INTO HABITE (ID_PERS, CODE_AGGLO, DEBUT, FIN) VALUES
(1, 'MA01', '2000-01-01', NULL),
(2, 'MA02', '2005-01-01', '2010-01-01'),
(3, 'MA03', '2010-01-01', NULL),
(4, 'MA04', '2015-01-01', NULL),
(5, 'MA05', '2020-01-01', NULL);


-- CREATION DE TABLE CAPITALE
CREATE TABLE CAPITALE (
ID_PAYS VARCHAR(2) NOT NULL,
CODE_AGGLO VARCHAR(5) NOT NULL,
PRIMARY KEY (ID_PAYS),
FOREIGN KEY (CODE_AGGLO) REFERENCES AGGLOMERATION (CODE)
);

-- INSERTION TABLE CAPITALE
INSERT INTO CAPITALE (ID_PAYS, CODE_AGGLO) VALUES
('MA', 'MA05');



--QUEST1
SELECT * FROM PERSONNE;

--QUEST 2
SELECT PRENOM FROM PERSONNE;

--QUEST3
SELECT PRENOM AS VORNAME FROM PERSONNE;


--QUEST4 
SELECT NOM, NAISSANCE FROM PERSONNE;


--QUEST 5 
SELECT NOM, YEAR(GETDATE()) - YEAR(NAISSANCE) AS AGE 
FROM PERSONNE;


--QUEST 6 
SELECT * FROM PERSONNE 
WHERE YEAR(GETDATE()) - YEAR(NAISSANCE) > 30;

